"""Write ARCHITECTURE.md: tech stack, entry points, deps, tree, module breakdown."""

from __future__ import annotations

from pathlib import Path
from typing import List

from repo_archaeologist.facts import Facts


def _format_loc(n: int) -> str:
    return f"{n:,} LOC"


def _tree_block(structure) -> List[str]:
    """Render a compact top-level tree."""
    lines: List[str] = []
    for d in sorted(structure.top_level_dirs):
        count = structure.dir_module_counts.get(d, 0)
        suffix = f"  ({count} source files)" if count else ""
        lines.append(f"- {d}/{suffix}")
    for f in sorted(structure.top_level_files):
        lines.append(f"- {f}")
    return lines


def render(facts: Facts) -> str:
    s = facts.structure
    d = facts.dependencies
    parts: List[str] = []

    parts.append(f"# Architecture — `{facts.repo_name}`\n")
    parts.append("> Auto-generated by `repo-archaeologist`. Heuristic; treat as a starting map, not ground truth.\n")

    # Tech stack
    parts.append("## Tech Stack\n")
    if s.languages:
        total = s.total_loc
        parts.append("| Language | LOC | Share |")
        parts.append("|---|---:|---:|")
        for lang, loc in sorted(s.languages.items(), key=lambda kv: kv[1], reverse=True):
            share = (loc / total * 100) if total else 0
            parts.append(f"| {lang} | {loc:,} | {share:.1f}% |")
        parts.append(f"\n**Total source LOC:** {total:,} across {s.source_file_count} source files ({s.file_count} files total).\n")
    else:
        parts.append("_No source files detected by extension. The repo may use a language not in the detector, or be non-code._\n")

    # Entry points
    parts.append("## Entry Points\n")
    if s.entry_points:
        for ep in s.entry_points:
            parts.append(f"- `{ep}`")
    else:
        parts.append("_No entry points detected. This may be a library, a collection of scripts, or a project with an unconventional layout._")
    parts.append("")

    # Dependencies
    parts.append("## Dependencies\n")
    if d.deps:
        parts.append(f"**{d.count} dependencies** across {len(d.by_ecosystem)} ecosystem(s): {', '.join(sorted(d.by_ecosystem))}.\n")
        for eco in sorted(d.by_ecosystem):
            parts.append(f"### {eco} ({len(d.by_ecosystem[eco])})\n")
            parts.append("| Package | Version |")
            parts.append("|---|---|")
            for dep in sorted(d.by_ecosystem[eco], key=lambda x: x.name)[:30]:
                parts.append(f"| {dep.name} | {dep.version_spec or '—'} |")
            if len(d.by_ecosystem[eco]) > 30:
                parts.append(f"\n_…and {len(d.by_ecosystem[eco]) - 30} more._")
            parts.append("")
    else:
        parts.append("_No dependency manifests detected (no requirements.txt, pyproject.toml, package.json, go.mod, Cargo.toml, or Gemfile)._\n")

    # Top-level tree
    parts.append("## Top-Level Layout\n")
    parts.append("```")
    parts.append(f"{facts.repo_name}/")
    for line in _tree_block(s):
        parts.append(line)
    parts.append("```\n")

    # Module breakdown (top dirs by source file count)
    parts.append("## Module Breakdown\n")
    if s.dir_module_counts:
        parts.append("| Directory | Source files |")
        parts.append("|---|---:|")
        for dir_name, count in sorted(s.dir_module_counts.items(), key=lambda kv: kv[1], reverse=True)[:15]:
            parts.append(f"| {dir_name} | {count} |")
        parts.append("")
    else:
        parts.append("_No source modules grouped by directory._\n")

    # Largest source files
    parts.append("## Largest Source Files\n")
    if s.largest_source_files:
        parts.append("| File | LOC |")
        parts.append("|---|---:|")
        for rel, loc in s.largest_source_files[:10]:
            parts.append(f"| {rel} | {loc:,} |")
        parts.append("")
    else:
        parts.append("_No source files found._\n")

    # Project hygiene flags
    parts.append("## Project Hygiene\n")
    flags = []
    flags.append(("README", "present" if s.has_readme else "**missing**"))
    flags.append(("LICENSE", "present" if s.has_license else "**missing**"))
    flags.append(("CI config", "present" if s.has_ci else "**missing**"))
    flags.append(("Dockerfile", "present" if s.has_dockerfile else "absent"))
    flags.append(("Lockfile", "present" if s.has_lockfile else "**missing**"))
    flags.append(("Tests", "detected" if s.has_tests else "**not detected**"))
    parts.append("| Signal | Status |")
    parts.append("|---|---|")
    for name, status in flags:
        parts.append(f"| {name} | {status} |")
    parts.append("")

    return "\n".join(parts)


def write(facts: Facts, out_dir: Path) -> Path:
    out = out_dir / "ARCHITECTURE.md"
    out.write_text(render(facts), encoding="utf-8")
    return out
